# Generated by Django 4.2.13 on 2026-09-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhod',
            name='profile_pic',
            field=models.ImageField(blank=True, default='perfil_1.png', null=True, upload_to=''),
        ),
    ]
